// flow-typed signature: 8d27461cd5a47a6990ee69d8f862c29d
// flow-typed version: <<STUB>>/hyperhtml_v^0.15.8/flow_v0.56.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'hyperhtml'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'hyperhtml' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'hyperhtml/hyperhtml' {
  declare module.exports: any;
}

declare module 'hyperhtml/min' {
  declare module.exports: any;
}

declare module 'hyperhtml/repl/js/main' {
  declare module.exports: any;
}

// Filename aliases
declare module 'hyperhtml/hyperhtml.js' {
  declare module.exports: $Exports<'hyperhtml/hyperhtml'>;
}
declare module 'hyperhtml/min.js' {
  declare module.exports: $Exports<'hyperhtml/min'>;
}
declare module 'hyperhtml/repl/js/main.js' {
  declare module.exports: $Exports<'hyperhtml/repl/js/main'>;
}
