// flow-typed signature: 41d0b07fbb4f10d48b26b5722adb99e2
// flow-typed version: <<STUB>>/tiny-cdn_v^0.7.0/flow_v0.56.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'tiny-cdn'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'tiny-cdn' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'tiny-cdn/cli/tiny-cdn-cli' {
  declare module.exports: any;
}

declare module 'tiny-cdn/cli/tiny-cdn-converger' {
  declare module.exports: any;
}

// Filename aliases
declare module 'tiny-cdn/cli/tiny-cdn-cli.js' {
  declare module.exports: $Exports<'tiny-cdn/cli/tiny-cdn-cli'>;
}
declare module 'tiny-cdn/cli/tiny-cdn-converger.js' {
  declare module.exports: $Exports<'tiny-cdn/cli/tiny-cdn-converger'>;
}
