// flow-typed signature: 79614b39f0b343e2a59c0277005cb81e
// flow-typed version: <<STUB>>/viperhtml_v^0.10.2/flow_v0.56.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'viperhtml'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'viperhtml' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'viperhtml/viperhtml' {
  declare module.exports: any;
}

// Filename aliases
declare module 'viperhtml/index' {
  declare module.exports: $Exports<'viperhtml'>;
}
declare module 'viperhtml/index.js' {
  declare module.exports: $Exports<'viperhtml'>;
}
declare module 'viperhtml/viperhtml.js' {
  declare module.exports: $Exports<'viperhtml/viperhtml'>;
}
